name: create-tag

on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest                
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      
      - name: Install semversioner
        run: pip3 install semversioner
        
      - name: Major version bump
        if: contains(github.event.pull_request.labels.*.name, 'major')
        run: semversioner add-change --type major --description '${{ github.event.pull_request.title }}'
      
      - name: Minor version bump
        if: contains(github.event.pull_request.labels.*.name, 'minor')
        run: semversioner add-change --type minor --description '${{ github.event.pull_request.title }}'

      - name: Patch version bump
        if: contains(github.event.pull_request.labels.*.name, 'patch')
        run: semversioner add-change --type patch --description '${{ github.event.pull_request.title }}'

      - name: Create release
        run: semversioner release

      - name: Update changelog
        run: semversioner changelog > CHANGELOG.md

      - name: Commit changes and push tag
        run: |
          env
          echo '${{ toJSON(github) }}'
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          TAG=$(semversioner current-version)
          git add .
          git commit -m "${TAG}"
          git push origin main
          git tag -a -m "Tagging for ${TAG}" "v${TAG}"
          git push origin "v${TAG}"
      